apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: src-app
  namespace: argo
  labels:
    name: src-app
spec:
  project: default
  source:
    repoURL: https://github.com/unique-dominik/anyrepo
    targetRevision: HEAD
    path: src-app/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: custom-integrations
  revisionHistoryLimit: 10
